services:
  api:
    # network_mode: ""
    extra_hosts:
    - "host.docker.internal:host-gateway"
    # - "host.docker.internal:10.252.3.149"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: soundlab-api
    platform: linux/amd64
    ports:
        - 3001:3001
    environment:
      SESSION_SECRET: asdfgsfgdsadfgsdfgsadfsdfasdfsfdg
      DB_NAME: slab
      # DB_HOST: 127.0.0.1
      # DB_HOST: localhost
      # DB_HOST: docker.for.mac.host.internal
      # DB_HOST: 172.19.0.1
      DB_HOST: host.docker.internal
      # DB_HOST: docker.for.mac.localhost
      DB_PORT: 3306
      DB_USER: slab
      DB_PASS: slab
      # CLIENT_SERVER: http://slab.loc
      CLIENT_SERVER: http://localhost:3000
      JWT_SECRET: '-D!s=oukAx@n/AKrisldTuZY?@x!Ok&lQTflnHk?38k4-j9`RBywDYpU<f5?BHMS'
      DEFAULT_LANGUAGE: en

      ADMIN_URL: http://slab.loc/admin
      PRERENDER_TOKEN:
      REACT_APP_SERVER: http://slab.loc

      # WS_SERVER_PORT: 3002
      # WS_SERVER_HOST: localhost
      # WS_SERVER_URI: subscriptions

      # EMAIL_SMTP_HOST=smtp.webfaction.com
      # EMAIL_SMTP_PORT=465
      # EMAIL_SMTP_SECURE=true
      # EMAIL_SMTP_USER=???
      # EMAIL_SMTP_PASSWORD=???
      # EMAIL_FROM=noreply@orphe.us
                          
      AWS_ACCESS_KEY_ID: AKIAFAKEKEY123456789
      AWS_SECRET_ACCESS_KEY: fakesecretaccesskey/realkeygoes+here
      AWS_REGION: us-east-1
      AWS_BUCKET: soundlab-uploads
      REACT_APP_BUCKET_URL: soundlab-uploads

    # for debugging
    # entrypoint: ["sh", "-c", "sleep infinity"]
    
  
        

        